'use strict';

const fp = require('fastify-plugin');

module.exports = fp(async (fastify) => {
    await fastify.register(require('@fastify/swagger'), {
        openapi: {
            info: {
                title: 'API Documentation',
                description: 'Generated by fastify-boilerplate-cli',
                version: '1.0.0',
            },
        },
    });

    await fastify.register(require('@fastify/swagger-ui'), {
        routePrefix: '/docs',
        uiConfig: {
            docExpansion: 'list',
        },
    });
});
