name: Build, Release, and Publish

on:
  push:
    branches:
      - main
  release:
    types: [created]
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: fastify-boilerplate-cli
          bump-minor-pre-major: true      # Optionally adjust to allow minor bumps on pre-major versions
          changelog-types: release        # Customize changelog format if needed
          token: ${{ secrets.GITHUB_TOKEN }}
          fork: false                     # Ensures PRs are in the same repo
          autorelease: true

  enable-auto-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Enable Auto-Merge for GitHub Actions Bot PR
        env:
          GH_PAT: ${{ secrets.GH_PAT }}   # Make sure to set this secret in GitHub Settings
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Get pull request details
          pr_data=$(curl -s -H "Authorization: token $GH_PAT" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER)

          # Check if the PR author is the GitHub Actions bot
          pr_author=$(echo "$pr_data" | jq -r '.user.login')
          if [ "$pr_author" = "github-actions[bot]" ]; then
            # Enable auto-merge
            curl -X PUT -H "Authorization: token $GH_PAT" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/merge \
                -d '{"merge_method": "squash"}'
          else
            echo "PR is not from GitHub Actions bot, skipping auto-merge."
          fi

  publish-npm:
    needs: release-please               # Ensures this job runs after release-please
    if: github.event_name == 'release'  # Runs only on releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
