name: Build, Release, and Publish

on:
  push:
    branches:
      - main
  release:
    types: [created]
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: fastify-boilerplate-cli
          bump-minor-pre-major: true
          changelog-types: release
          token: ${{ secrets.GITHUB_TOKEN }}
          fork: false
          autorelease: true

  enable-auto-merge:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'github-actions[bot]' }}  # Run only for GitHub Actions bot PRs
    steps:
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Enable auto-merge for GitHub Actions Bot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: enable-auto-merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
