name: Build, Release, and Publish

on:
  push:
    branches:
      - main
  release:
    types: [created]
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: fastify-boilerplate-cli
          bump-minor-pre-major: true
          changelog-types: release
          token: ${{ secrets.GITHUB_TOKEN }}
          fork: false
          autorelease: true

  enable-auto-merge:
    needs: release-please
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push' 
    steps:
      - name: Enable Auto-Merge for GitHub Actions Bot PR
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          pr_data=$(curl -s -H "Authorization: token $GH_PAT" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER)

          echo "Pull Request Data: $pr_data"  # For debugging
          
          pr_author=$(echo "$pr_data" | jq -r '.user.login')
          if [ "$pr_author" = "github-actions[bot]" ]; then
            response=$(curl -X PUT -H "Authorization: token $GH_PAT" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/merge \
                -d '{"merge_method": "squash"}')
            echo "Merge Response: $response"  # For debugging
          else
            echo "PR is not from GitHub Actions bot, skipping auto-merge."
          fi

  publish-npm:
    needs: enable-auto-merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
